# Generated by Django 2.0.1 on 2018-01-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0002_auto_20180120_0131'),
        ('productos', '0002_auto_20180120_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depositos.Deposito'),
        ),
    ]
